# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test php

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Setup PHP

        uses: shivammathur/setup-php@v2

        with:
        
          php-version: '8.3'

      - name: Install Dependencies

        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
